# Change these first
owner: Eotel # Your GitHub organization or username, where this repository lives
repo: pxe-yokohama-rpi-uptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /pxe-yokohama-rpi-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: pxe-yokohama-rpi-uptime
  introTitle: "Check RasPi Status"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/eotel/pxe-yokohama-rpi-uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
